sdk_names:
  model_name: opensearch
ignore:
  resource_names:
    - Package
    # - Domain
    - OutboundConnection
    - VpcEndpoint
  field_paths:
    # SnapshotOptions is irrelevant for OpenSearch 5.3+
    - CreateDomainInput.SnapshotOptions
    - CreateDomainInput.Name
    - CreateDomainInput.EncryptionAtRestOptions
    - CreateDomainInput.VPCOptions
    - DeleteDomainInput.Name
resources:
  Domain:
    renames:
      operations:
        CreateDomain:
          input_fields:
            DomainName: Name
            TagList: Tags
        DeleteDomain:
          input_fields:
            DomainName: Name
        DescribeDomain:
          input_fields:
            DomainName: Name
    fields:
      ClusterConfig:
        is_read_only: true
        from:
          operation: DescribeDomain
          path: DomainStatus.ClusterConfig
      EngineVersion:
        is_read_only: true
        from:
          operation: DescribeDomain
          path: DomainStatus.EngineVersion
      NodeToNodeEncryptionOptions:
        is_read_only: true
        from:
          operation: DescribeDomain
          path: DomainStatus.NodeToNodeEncryptionOptions
      AdvancedOptions:
        is_read_only: true
        from:
          operation: DescribeDomain
          path: DomainStatus.AdvancedOptions
      DomainEndpointOptions:
        is_read_only: true
        from:
          operation: DescribeDomain
          path: DomainStatus.DomainEndpointOptions
      AdvancedSecurityOptions:
        is_read_only: true
        from:
          operation: DescribeDomain
          path: DomainStatus.AdvancedSecurityOptions
      AutoTuneOptions:
        is_read_only: true
        from:
          operation: DescribeDomain
          path: DomainStatus.AutoTuneOptions
      CognitoOptions:
        is_read_only: true
        from:
          operation: DescribeDomain
          path: DomainStatus.CognitoOptions
      AccessPolicies:
        is_read_only: true
        from:
          operation: DescribeDomain
          path: DomainStatus.AccessPolicies
    exceptions:
      errors:
        404:
          code: ResourceNotFoundException
      terminal_codes:
        - ValidationException
